import os 
import time

os.system('python audio.py')
time.sleep(1)
print('audio file has been created')
os.system('python utilities.py')
time.sleep(1)
print('output folder ready to create video')
os.system('python text_to_video.py')
time.sleep(1)
os.system('del -r downloads')
print('deleted files from downloads')
time.sleep(1)
os.system('del -r output')
print('deleted files from output')
time.sleep(1)
os.system('del output.mp4')
print('deleted output.mp4')
time.sleep(1)
os.system('del list.txt')
print('deleted list.txt')
time.sleep(1)
os.system('del text.mp3')
print('deleted text.mp3')
time.sleep(1)